### ISSUE TITLE
Chapter 7 exercise 3 solution gets stuck in k_work_submit_to_queue

### ISSUE THREAD

**Issue by ArjunSingh13** [NordicDeveloperAcademy/ncs-fund#1]
Below is the code:

https://github.com/NordicDeveloperAcademy/ncs-fund/tree/main/v2.x.x/lesson7/fund_less7_exer3_solution

**Comment by NordicDeveloperAcademy** [comment]
Hi ArjunSingh13, I am unable to replicate the problem reported. Which nRF Connect SDK version and development kit were you using? 
It might be that in Step 9, you forgot to comment out emulate_work(); ?
